import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SideBar from "@/components/dashboard/sidebar";
import DashNav from "@/components/dashboard/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div className="flex flex-row h-screen w-screen bg-gray-100">
                <SideBar/>
            <div className="flex-1 w-full h-full overflow-y-scroll">
                <DashNav/>
                <div className="p-2">
                    {children}
                </div>
            </div>
       </div>
      </body>
    </html>
  );
}
